language: php

php:
  - 5.5
  - 5.6

branches:
  only:
    - master

before_script:
  - pear channel-discover pear.phing.info
  - pear install phing/phing
  - phpenv rehash
  - openssl aes-256-cbc -K $encrypted_7d50c4001e84_key -iv $encrypted_7d50c4001e84_iv -in id_rsa.enc -out id_rsa -d

script:
    - phing -f build.xml phplint

install:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
